export const test1Data = [
  {
    module: 1,
    content1:
      "Although oil shocks—such as the 460% rise in oil prices from April to September of 1973—can strongly affect individual consumers, Ghadebo Oladosu and colleagues have shown that at the level of national economies, their effects are often quite _____ . The effect of recent oil shocks on the gross domestic product of China, for example, was only slightly greater than zero.",
    content2: "Which choice completes the text with the most logical and precise word or phrase?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "subdued",
    answerB: "variable",
    answerC: "beneficial",
    answerD: "persistent",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Vocabulary",
    tag2: "Blank",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      'A number of recording artists ________ distinctions between Indigenous music and other musical styles. For example, Choctaw singer-songwriter Samantha Crain incorporated elements of Choctaw hymns into folk-pop on her single "When We Remain, " and Oji-Cree/Mikmaq musician Anachnid combined Indigenous flute and powwow vocals with electronic music on her album Dreamweaver.',
    content2: "Which choice completes the text with the most logical and precise word or phrase?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "disguise",
    answerB: "reject",
    answerC: "observe",
    answerD: "replace",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "Vocabulary",
    tag2: "Blank",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "Though most hoaxes perpetrated as jokes by mischievous users of Wikipedia, an online encyclopedia that almost anyone can freely edit, have quickly been detected and removed, a few entries that knowledgeable and attentive readers should have realized were ____, such as those for the American new wave band Transformatix and the 20th-century Vietnamese poet Vien Che, persisted on the site for years before they were finally recognized as falsehoods and deleted.",
    content2: "Which choice completes the text with the most logical and precise word or phrase?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "spurious",
    answerB: "prolonged",
    answerC: "scrupulous",
    answerD: "undetected",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Vocabulary",
    tag2: "Blank",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "The following text is adapted from the 1895 poem “Ojistoh” by Emily Pauline Johnson, a Kanienkahagen (Mohawk) writer also known as Tekahionwake.",
    content2:
      "I am Ojistoh, I am she, the wife\nOf him whose name breathes bravery and life\nAnd courage to the tribe who calls him chief.\nI am Ojistoh, his white star, and he\nIs land, and lake, and sky—and soul to me.",
    content3: "As used in the text, what does the word “breathes” most nearly mean?",
    content4: "",
    content5: "",
    answerA: "Imparts",
    answerB: "Renounces",
    answerC: "Assents",
    answerD: "Absorbs",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Vocabulary",
    tag2: "Context",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "New and interesting research conducted by Suleiman A. Al-Sweedan and Moath Alhaj is inspired by their observation that though studies of the effect of high attitude on blood chemistry are ______, the effect on blood chemistry of living in locations below sea level, such as the California towns of Brawley and Holtville, received comparatively little notice.",
    content2: "Which choice completes the text with the most logical and precise word or phrase?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "equivocal",
    answerB: "abundant",
    answerC: "preliminary",
    answerD: "sporadic",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "Vocabulary",
    tag2: "Blank",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "Vertical gene transfer involves the transmission of genetic material from a parent to offspring; horizontal gene transfer, on the other hand, involves the exchange of genetic material between organisms not in a parent-offspring relationship. While horizontal gene transfer is common among prokaryotes—single-celled organisms, such as the bacteria Brevundimonas diminuta and Massilia timonae—it has rarely been observed among eukaryotes (multicellular organisms). However, new studies suggest that horizontal gene transfer is more common in eukaryotes than originally thought.",
    content2: "Which choice best states the function of the underlined sentence in the text as a whole?",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "It contrasts the frequency with which a biological phenomenon has been detected in two categories of organisms.",
    answerB: "It argues that two biological phenomena are more similar than they may initially appear to be.",
    answerC: "It explains why a common perception of a biological process is flawed.",
    answerD: "It indicates a distinction between the mechanics of two kinds of biological processes.",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Function",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "Can tomato plants grow on Mars? Can pea plants? You might think the answer to these questions is obviously no, but researchers in Europe recently showed that many common plant species can thrive in soil designed to simulate Martian conditions, as long as water is supplied. In fact, some species actually did better in Martian soil than in Earth soil: 84 percent of tomato plants grown in simulated Martian soil developed leaves, compared with 57 percent that did when planted in soil from their home planet.",
    content2: "Which choice best states the main purpose of the text?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "To answer long-standing questions about how Martian soil conditions can be simulated on Earth",
    answerB:
      "To explain an important study of differences in the composition of Martian soil and the composition of Earth soil",
    answerC: "To present a surprising finding about plants grown in soil intended to be similar to Martian soil",
    answerD: "To discuss an unexpected result about the role of water in plants grown in simulated Martian soil",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Purpose",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "Arthropods—horseshoe shrimp, luna moths, and many other invertebrate animals—have a nervous system made up of a brain, nerve cord, and other nerves. Researchers have gained insights about this system in ancient arthropods from traces found in various fossils. For example, in a study of two fossils of the extinct arthropod species Molasonia symmetrica, Javier Ortega-Hernández, Rudy Lermey-Auhril, and team observed clear signs of a nerve cord. They also saw palpable indications of a synganglion, a brain-like mass of nerves. Researchers hope to identify more features of the nervous systems of prehistoric arthropods as additional fossils are found.",
    content2: "Which choice best states the main idea of the text?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "Fossil evidence can contribute to the understanding of the nervous system in ancient arthropods.",
    answerB: "Researchers need to focus on finding more fossils of ancient arthropods.",
    answerC: "Newly discovered fossils suggest that ancient luna moths and ancient horseshoe shrimp had spines.",
    answerD: "There are several similarities between the brains of luna moths and the brains of horseshoe shrimp.",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Idea",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "In a study by Mika R. Moran, Daniel A. Rodriguez, and colleagues, residents of Quito, Ecuador, and Buenos Aires, Argentina, were surveyed about parks in their cities. Of the 618 respondents from Quito, 82.9% indicated that they use the city's parks, and of the 683 respondents from Buenos Aires, 69.9% indicated using city parks. Given that the percentage of Quito respondents who reported having access to other desired amenities near parks was much lower than that reported by Buenos Aires respondents, the difference in park use can't be explained by Quito residents having more access to desired nonpark amenities near parks.",
    content2: "Which choice best describes the main idea of the text?",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "The study's findings suggest that an increase in the number of amenities near city parks would likely increase park use in Quito but not in Buenos Aires.",
    answerB:
      "Although the study found that a greater proportion of residents use parks in Quito than in Buenos Aires, that difference isn't due to greater access to amenities near parks in Quito.",
    answerC:
      "The study's finding that a greater proportion of residents use parks in Quito than in Buenos Aires is partly due to the greater prevalence of parks in Quito.",
    answerD:
      "Even though the study found that parks in Buenos Aires are more likely to be close to other amenities than parks in Quito are, Quito has more amenities overall than Buenos Aires does.",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "Idea",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "The following text is adapted from Jerome K. Jerome's 1889 novel Three Men in a Boat (To Say Nothing of the Dog).",
    content2:
      "We people are creatures of the sun. We love light and life. That is why we crowd into the towns and cities, and the country grows more and more deserted every year. In the sunlight—in the daytime, when Nature is alive and busy all around us, we like the open hill-sides and the deep woods well enough; but in the night, when our Mother Earth has gone to sleep, and left us waking, oh! the world seems so lonesome, and we get frightened, like children in a silent house. Then we sit and sob, and long for the gas-lit streets, and the sound of human voices, and the answering throb of human life.",
    content3: "Which choice best states the main purpose of the text?",
    content4: "",
    content5: "",
    answerA: "To caution people not to be so quick to dismiss the natural beauty that can be found in rural areas.",
    answerB: "To indicate that people sometimes experience feelings of isolation in crowded areas.",
    answerC:
      "To demonstrate that most people tend to prefer to be in towns and cities during the day and in the country at night.",
    answerD: "To address common traits that motivate many people to choose to live in urban environments.",
    correctAnswer: "D",
    testType: "Reading and Writing",
    tag1: "Purpose",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "Water flowing around an obstruction creates vortices (patterns of swirls) of varying size. By detecting the vortices, fish can determine the size and position of the obstruction. Testing by Yuzo R. Yanagisawa, Otar Akanyeti, and James C. Liao using models of three head shapes—narrow (low ratio of width to length), intermediate, and wide (high ratio of width to length)—showed that for medium-sized vortices, fish with wide heads would be least able to distinguish between vortices and general turbulence in the water. A second research team has therefore hypothesized that in low-visibility conditions, wider-headed fish will be less likely than narrower-headed fish to detect obstructions.",
    content2: "Which finding, if true, would most directly support the second research team's hypothesis?",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "A study using obstructions that created medium-sized vortices in low-visibility conditions found that the wider-headed anglerfish (Lophiodes monodi) bumped into obstructions more often than the narrower- headed Lobocheilos rhabdoura did.",
    answerB:
      "A study using obstructions that created medium-sized vortices in low-visibility conditions found that some specimens of Lobocheilos rhabdoura, which has a relatively narrow head, bumped into the obstructions more often than other specimens of the same fish did.",
    answerC:
      "A study using obstructions that created medium-sized vortices in low-visibility conditions found that the anglerfish (Lophiodes monodi), which has a relatively wide head, bumped into more than half of the obstructions.",
    answerD:
      "A study using obstructions that created medium-sized vortices in low-visibility conditions found that the arrower-headed Lobocheilos rhabdoura bumped into the obstructions just as often as the wider-headed anglerfish (Lophiodes monodi) did.",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Finding",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1: "Reported Annual Travel Distances in Four Studies of Migrating Animal Populations",
    content2: "@@89-1-12@@",
    content3:
      "Some studies of migrating animals measure how far the animals travel in a year by fitting individuals with GPS tracking collars. Other studies track annual round-trip distance (RTD), which is equal to double the distance separating the two habitats a population migrates between each year. A researcher argues that since GPS records all of an animal's movements, using the GPS method to track a population would result in significantly higher recorded travel distances than using the RTD method would. For example, it's very likely that the distance reported for the ____",
    content4: "Which choice most effectively uses data from the table to complete the example?",
    content5: "",
    answerA: "Mongolian gazelle would be greater than 5,067 kilometers if the GPS method had been used.",
    answerB: "Khulan would be greater than 2,356 kilometers if the RTD method had been used.",
    answerC: "Mongolian gazelle would be less than 600 kilometers if the GPS method had been used.",
    answerD: "Khulan would be less than 5,067 kilometers if the RTD method had been used.",
    correctAnswer: "D",
    testType: "Reading and Writing",
    tag1: "Data",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1: "Defensive Behavior and Reproductive Traits of Select Bird Species",
    content2: "@@89-1-13@@",
    content3:
      "In an extensive review of existing literature, Lena de Framond and team cataloged the prevalence of broken-wing display— a defensive behavior observed in Plovialis dominica (American golden plover) and many other species—throughout the Aves class. Documentation of the display in 285 species across 52 families suggests the behavior likely evolved independently multiple times, prompting the team to consider ecological and life-history characteristics with hypothesized associations to the behavior's emergence, including traits related to reproduction investment and future reproduction potential. Based on their review of those traits, the team concluded that _____",
    content4: "Which choice most effectively uses data from the table to complete the conclusion?",
    content5: "",
    answerA:
      "incubation duration and capacity for multiple broods are more strongly associated with the use of broken- wing display than the number of parental incubators is.",
    answerB:
      "among species with more than one parental incubator, the use of broken-wing display is associated with greater incubation duration.",
    answerC:
      "capacity for multiple broods, number of parental incubators, and incubation duration are equally associated with the use of broken-wing display.",
    answerD:
      "broken-wing display is most often observed in species with less opportunity to reproduce in a year due to longer incubation periods.",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Data",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1: "Percentage of Nonhexagonal Cells in Hives of Three Honeybee Species",
    content2: "@@89-1-14@@",
    content3:
      "Honeybee hives consist mainly of hexagonal (six-sided) units called cells, in which queens lay eggs. Hexagonal cells for eggs that develop into nonreproductive workers are smaller than those for eggs that develop into reproductive drones, though the size difference varies by species. Difference in cell size results in a construction problem—it's hard to neatly connect sections of small cells to sections of large cells—that worsens as the difference increases. To fill in gaps between the sections when building a hive, bees rely on cells that have more or fewer than six sides. A student studying beehive structure consults data on three species, concluding that _______",
    content4: "Which choice most effectively uses data from the graph to complete the student's conclusion?",
    content5: "",
    answerA:
      "both the western honeybee and the black dwarf honeybee probably reserve eight-sided cells for drone eggs, while the dwarf honeybee likely deposits drone eggs in seven-sided cells.",
    answerB:
      "the western honeybee probably relies on more geometrical shapes when constructing cells than either the dwarf honeybee or the black dwarf honeybee does.",
    answerC:
      "cells for worker eggs are probably closer in size to cells for drone eggs in the hives of the western honeybee than in the hives of the dwarf honeybee and the black dwarf honeybee.",
    answerD:
      "the percentage of hexagonal cells is probably slightly lower in the hives of the western honeybee than in the hives of the dwarf honeybee and the black dwarf honeybee.",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Data",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "Pigments give paints and dyes their color. Ocher is a mineral-based pigment used to make several colors, including red. Red ocher gets its color from iron oxide. Pigments can also be plant-based; plant-based pigments contain a high level of carbon. In a 2023 study, archaeologists tested the red pigment on decorated beads made by members of the Natufian culture approximately 15,000 years ago. The test showed that the pigment found on several beads contained no iron but had a high level of carbon. This finding led the researchers to conclude that _____",
    content2: "Which choice most logically completes the text?",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "the pigments used by the Natufian beadmakers likely came from plants because ocher was difficult to find.",
    answerB:
      "the Natufian beadmakers preferred to use plant-based pigments because they are much brighter than mineral-based pigments.",
    answerC:
      "the Natufian beads examined in the study are the oldest surviving examples of the use of plant-based pigments for decorating beads.",
    answerD:
      "the Natufian beadmakers used plant-based pigments rather than ocher to decorate some of the beads examined in the study.",
    correctAnswer: "D",
    testType: "Reading and Writing",
    tag1: "Complete",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "Topographical prominence is a measure of a mountain's independence from other mountains. Having 15,118 feet of prominence, ______",
    content2: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "geographers have ranked Nanga Parbat, a peak located in Pakistan, as the world's 14th most prominent mountain.",
    answerB:
      "geographers have identified Nanga Parbat as the 14th most prominent peak in the world, located in Pakistan.",
    answerC:
      "Nanga Parbat, ranked by geographers, holds the 14th position among the world's most prominent mountains.",
    answerD:
      "the list of the world's most prominent mountains, as ranked by geographers, includes Nanga Parbat at number 14.",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Grammar",
    tag2: "Modifier",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "Works by Luis Cruz Azaceta and Luis Jiménez were featured in the Smithsonian American Art Museum's exhibition Our America: The Latino Presence in American Art. This 2013 exhibition celebrated the diverse achievements artists of _____ Latin American descent.",
    content2: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "of,",
    answerB: "of;",
    answerC: "of:",
    answerD: "of",
    correctAnswer: "D",
    testType: "Reading and Writing",
    tag1: "Grammar",
    tag2: "Punctuation",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "Trade was vital to the Zhou dynasty, which reigned in China from around 1045 BCE 221 BCE. Its people bronze, ____ jade, and silk to sell to neighboring societies. In exchange, they received valuable items, such as wood, spices and textiles.",
    content2: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "produced",
    answerB: "will produce",
    answerC: "produce",
    answerD: "are producing",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Grammar",
    tag2: "Verb Choice",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "The Globe Theatre in London is a reconstruction of the famed venue where many of Shakespeare's plays were first performed. In 1613, a prop cannon ______ during a performance and ignited the Globe's thatched roof. No one was hurt, but in two hours the original Globe was gone.",
    content2: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "has malfunctioned",
    answerB: "malfunctions",
    answerC: "will malfunction",
    answerD: "malfunctioned",
    correctAnswer: "D",
    testType: "Reading and Writing",
    tag1: "Grammar",
    tag2: "Verb Choice",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "Upper Fruitland Chapter, which covers 83,400 acres, is one of the 110 chapters of the Navajo ______ Diné bizaad (the Navajo language), the chapter is called Doo Alk'aai.",
    content2: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "Nation. In",
    answerB: "Nation, in",
    answerC: "Nation in",
    answerD: "Nation and in",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Grammar",
    tag2: "Punctuation",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "As a leader of the Nation Woman Suffrage Association in the late 1800s, Olympia Brown of ______ an important role in the campaign to secure voting rights for US women.",
    content2: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "Connecticut; played",
    answerB: "Connecticut: played",
    answerC: "Connecticut played",
    answerD: "Connecticut. Played",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Grammar",
    tag2: "Punctuation",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "Famous for its four-degree tilt, the leaning Garisenda Tower is a popular attraction in Bologna's city center. However, measurements taken in 2023 showed that the tower was rotating in a concerning way. ____ city officials closed the area around the tower so experts could explore solutions to stabilize the historical twelfth-century structure.",
    content2: "Which choice completes the text with the most logical transition?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "For example,",
    answerB: "In comparison,",
    answerC: "As a result,",
    answerD: "Similarly,",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Transition",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "When languages are no longer spoken, they are considered extinct. _______ the Umbrian language went extinct around the first century BCE, though it was once widely spoken in parts of central Italy.",
    content2: "Which choice completes the text with the most logical transition?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "For example,",
    answerB: "In conclusion,",
    answerC: "Admittedly,",
    answerD: "Therefore,",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Transition",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1:
      "Scientists studying asteroid deflection have focused on secondary objects such as S/2005 (488453), a moonlet orbiting the near-Earth asteroid 1994 XD. In 2022 NASA intentionally crashed a probe into just such an object, the moonlet Dimorphos. ______ Dimorphos's orbital period around the near-Earth asteroid Didymos was permanently altered.",
    content2: "Which choice completes the text with the most logical transition?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "In addition,",
    answerB: "Consequently,",
    answerC: "In comparison,",
    answerD: "Specifically,",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "Transition",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1: "While researching a topic, a student has taken the following notes:",
    content2:
      "- Dinosaur fossil specimens can be found at science museums all over the world.  - Many dinosaur fossil specimens are given nicknames.  - The Great Plains Dinosaur Museum and Field Station in Malta, Montana, houses a dinosaur fossil specimen nicknamed Roberta.  - Roberta lived in the Late Cretaceous period, which ended more than 65 million years ago.  - It is a member of the genus Brachylophosaurus.  - The student wants to provide an example of a dinosaur fossil specimen's nickname.",
    content3:
      "The student wants to provide an example of a dinosaur fossil specimen's nickname. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    content4: "",
    content5: "",
    answerA:
      "Roberta is the nickname of a Brachylophosaurus fossil specimen housed at The Great Plains Dinosaur Museum and Field Station in Malta, Montana.",
    answerB:
      "Dinosaur fossil specimens can be found at museums all over the world, and many of these specimens are given nicknames.",
    answerC:
      "A Brachylophosaurus fossil specimen from the Late Cretaceous period, which ended more than 65 million years ago, is housed at the Great Plains Dinosaur Museum and Field Station in Malta, Montana",
    answerD:
      "Nicknames are given to many dinosaur fossil specimens, including one housed at a museum in Malta, Montana.",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Notes",
    tag2: "Example",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1: "While researching a topic, a student has taken the following notes:",
    content2:
      '- The A.M. Turing Award is a prestigious award given for "major contributions of lasting importance to computing".  - Manuel Blum won the award in 1995 for contributions to the foundations of computational complexity theory.  - Raj Reddy won the award in 1994 for pioneering the development of large-scale artificial intelligence systems.',
    content3:
      "The student wants to emphasize the order in which Manuel Blum and Raj Reddy won the A.M. Turing Award. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    content4: "",
    content5: "",
    answerA: "Raj Reddy won the A.M. Turing Award in 1994; Manuel Blum won it later, in 1995.",
    answerB:
      'Manuel Blum and Raj Reddy both won the A.M. Turing Award, which is given for “major contributions of lasting importance to computing".',
    answerC: "It was in 1994 that Raj Reddy won the A.M. Turing Award.",
    answerD: "In 1995, Manuel Blum won the A.M. Turing Award to the foundations of computational complexity theory.",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Notes",
    tag2: "Emphasize",
    tag3: "",
    tag4: "",
  },
  {
    module: 1,
    content1: "While researching a topic, a student has taken the following notes:",
    content2:
      "- Lighthouses send out crucial light signals to help ships and other watercraft navigate at night.  - Before automation, lighthouses were run by lighthouse keepers.  - Barbara Mabrity was the lighthouse keeper at Key West Light in Florida.  - She held this position from 1832 tο 1862. Flora McNeil was the lighthouse keeper at Bridgepost Breakwater Light in Connecticut.  - She held this position from 1904 to 1920.",
    content3:
      "The student wants to emphasize a difference between the two lighthouse keepers. Which choice effectively uses relevant information from the notes to accomplish this goal?",
    content4: "",
    content5: "",
    answerA:
      "Barbara Mabrity and Floral McNeil both played crucial roles in ensuring safe navigation for watercraft in past centuries.",
    answerB: "From 1832 to 1862, the nighttime waters of Florida were made more navigable thanks to Barbara Mabrity.",
    answerC: "Barbara Mabrity worked as a lighthouse keeper in an earlier century than did Flora McNeil.",
    answerD:
      "As the lighthouse keeper at Bridgeport Breakwater Light, Flora McNeil helped watercraft navigate at night.",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Notes",
    tag2: "Emphasize",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "Writer Lydia Davis observed that while traditional literary forms, such as the novel, are recognizable as such even as they evolve, there are more _______ forms that might, for example, borrow elements from both fables and realist narratives to make something unconventional. The late-period pieces of James Tate arguably fit in this category, since they straddle the line between prose and poetry.",
    content2: "Which choice completes the text with the most logical and precise word or phrase?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "dipersed",
    answerB: "customary",
    answerC: "amorphous",
    answerD: "neutral",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Vocabulary",
    tag2: "Blank",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "Both amphibians and cartilaginous fish can detect electrical fields around them, but the ___ of their mechanisms differs substantially. Whereas cartilaginous fish can detect fields generated by bad-weather atmospheric conditions, those are many times stronger than fields created by moving prey, which amphibians are sensitive enough to detect.",
    content2: "Which choice completes the text with the most logical and precise word or phrase?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "orientation",
    answerB: "magnitude",
    answerC: "gathering",
    answerD: "firmness",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "Vocabulary",
    tag2: "Blank",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "To assist with the development of new water-repellent materials for aviation and other applications, a team including both engineers and entomologists conducted a study of the water-repellent properties of cicada wings. The team explained that the ____ experts in these two disciplines resulted in a more comprehensive approach than independent efforts by experts in either discipline could have achieved.",
    content2: "Which choice completes the text with the most logical and precise word or phrase?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "exaggeration of",
    answerB: "distrust among",
    answerC: "skepticism toward",
    answerD: "collaboration between",
    correctAnswer: "D",
    testType: "Reading and Writing",
    tag1: "Vocabulary",
    tag2: "Blank",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "Though John Crowley, author of The Translator, is not as well known as the most commercially successful American writers of the past fifty years, his work has had several influential champions, including the poet James Merrill and the literary critic Harold Bloom. In his afterword to Crowley's book Little, Big, Bloom argues that the novel adroitly blends what playwright Friedrich Schiller termed the naive and sentimental modes—while Schiller thought works could be classified as either naive (seeking to describe reality) or sentimental (seeking to develop ideas), Little, Big fuses both modes of writing.",
    content2: "Which choice best describes the overall structure of the text?",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "It mentions a writer whose work is not widely known, presents two people who hold a positive opinion of that writer, and gives a reason why one of those people holds that opinion.",
    answerB:
      "It describes a writer's successful career, presents two literary figures who were supporters of that writer's career, and explains why the writer was able to achieve what he did.",
    answerC:
      "It identifies a writer whose work is regarded as difficult to read, brings up two admirers of that writer, and discusses how they make the writer's work more accessible to readers.",
    answerD:
      "It accounts for a writer's lack of popular appeal, cites a literary figure who appreciates that writer, and summarizes the qualities that make the writer's work unique.",
    correctAnswer: "D",
    testType: "Reading and Writing",
    tag1: "Structure",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "Paintings by the Florida Highwaymen—an informal collective of prolific landscape artists active in Florida during the 1950s and '60s—are recognizable by their reiteration of the same general compositional structures and subjects: backcountry pines and fire sky sunsets, to name two. But there was room for individuation: Robert Butler's Deer in Clearing, for example, may resemble other Highwaymen paintings at first glance, but his works stand out for their detailed rendering of wildlife and dramatic lighting.",
    content2: "Which choice best describes the overall structure of the text?",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "It offers historical context that accounts for a particular group of artists' shared style and then indicates the circumstances under which several members of that group began exploring more unconventional themes.",
    answerB:
      "It describes the common perception that a particular group of artists' works are derivative and then provides a specific piece of evidence that reinforces that perception.",
    answerC:
      "It describes an aesthetic framework shared by a particular group of artists and then makes and illustrates the claim that individuals introduced variations within that framework.",
    answerD:
      "It explains how a particular group of artists began collaborating and then recounts how one member of that group became especially influential among them.",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Structure",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "The following text is from Anthony Trollope's 1855 novel The Warden. Charles James is the son of a high-ranking clergy member.",
    content2:
      "Charles James was an exact and careful boy, he never committed himself; he well knew how much was expected from the eldest son of the Archdeacon of Barchester, and was therefore mindful not to mix too freely with other boys. He had not the great talents of his younger brothers, but he exceeded them in judgment and propriety of demeanour; his fault, if he had one, was an over attention to words instead of things; there was a thought too much finesse about him, and, as even his father sometimes told him, he was too fond of a compromise.",
    content3: 'Which choice best states the function of the phrase "if he had one" in the text as a whole?',
    content4: "",
    content5: "",
    answerA:
      "It concedes that Charles James's attempts to gain the approval of those who know him are sometimes to little avail.",
    answerB:
      "It signals a shift in focus from describing Charles James's fine traits to criticizing his tendency to excessively fear being the source of conflict.",
    answerC:
      "It acknowledges that the qualities in Charles James the narrator goes on to describe may not actually be undesirable characteristics.",
    answerD: "It anticipates readers' objections to the narrator's criticism of Charles James's faults.",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Function",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "The Surgeon's Mate, first published in 1980, is a novel in Patrick O'Brian's Aubrey/Maturin series, which includes twenty books plus an unfinished fragment of a twenty-first. Like the rest of the books in the series, The Surgeon's Mate has a rather abrupt ending, but the following book, The Ionian Mission, picks up neatly where The Surgeon's Mate leaves off. Thus, the sudden ending is only an issue if one considers the books as independent texts—the Aubrey/Maturin series is best thought of as a single incredibly long work, similar to other multivolume stories, such as Anthony Powell's A Dance to the Music of Time.",
    content2: "Which choice best states the main idea of the text?",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "The Surgeon's Mate and The Ionian Mission are two of the most complex of O'Brian's novels due in part to their unconventional structures.",
    answerB:
      "Over time, the Aubrey/Maturin series has acquired the same eminence among critics as works like A Dance to the Music of Time that have similar structures.",
    answerC:
      "Many readers find the Aubrey/Maturin novels to be remarkably entertaining despite flaws in the novels' structures.",
    answerD:
      "A certain understanding of the structures of the novels in the Aubrey/Maturin series is helpful if one wishes to appreciate the series.",
    correctAnswer: "D",
    testType: "Reading and Writing",
    tag1: "Idea",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1: "The following text is from Ralph Waldo Emerson's 1841 essay \"The Method of Nature.",
    content2:
      "The scholars are the priests of that thought which establishes the foundations of the earth. No matter what is their special work or profession, they stand for the spiritual interest of the world, and it is a common calamity if they neglect their post in a country where the material interest is so predominant as it is in America.",
    content3: "Which choice best states the main idea of the text?",
    content4: "",
    content5: "",
    answerA:
      "Military experience encourages Americans to contemplate aspects of human life that they would not choose to otherwise.",
    answerB:
      "In a country whose citizens are largely preoccupied with tangible gains, it is crucial that some people work to foster and preserve ideas.",
    answerC: "It is unfortunate that so many intellectuals are concerned with material things rather than ideas.",
    answerD: "Many descriptions of the role of scholars in society unfairly diminish their importance.",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "Idea",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1: "Text 1",
    content2:
      "Toni Morrison's 1973 novel Sula, a tale of two women's lives set in small-town Ohio from the 1910s to the 1960s, has been described as historical fiction. While it's inarguable that Morrison's book takes place in the past rather than in her own time, Sula is much richer and more complicated than the mere re-creation of the past suggested by the term \"historical fiction. ",
    content3: "Text 2",
    content4:
      "Some literary critics dismiss historical fiction as a shallow genre in which writers show off their knowledge of period details rather than tell meaningful stories. But historical fiction can be used to explore profound themes and complex characters. In fact, many writers find that writing about the past gives them a creative freedom they'd lack if they wrote about the present.",
    content5:
      "Based on the texts, how would the author of Text 2 most likely respond to the claim about Sula advanced by the author of Text 1?",
    answerA: "By arguing that Morrison displays a thorough knowledge of historical details in Sula",
    answerB:
      "By asserting that dissatisfaction with describing Sula as historical fiction reflects a misunderstanding of the genre",
    answerC:
      "By conceding that the genre of historical fiction contains many works that are less sophisticated than Sula is",
    answerD: "By claiming that the author of Text 1 has underestimated the richness and complexity of Sula",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "MultiText",
    tag2: "Response",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "Biologist Grace Herzel and colleagues conducted a study of how butterfly color and weather conditions relate to butterfly behavior, which wouldn't have been possible without data gathered by students and other amateur science enthusiasts in the community. Considering over three years' worth of data, the researchers found that white butterflies were observed on green flowers more often than any other butterflies were, and that butterflies were observed to feed more often on cloudy days than on other days.",
    content2:
      "According to the text, which factors seemed to be linked to the behavior of butterflies in Grace Herzel and colleagues' study?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "Weather conditions but not butterfly color",
    answerB: "Butterfly color but not weather conditions",
    answerC: "Both butterfly color and weather conditions",
    answerD: "Neither butterfly color nor weather conditions",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Reading",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "Memoirs of Elleanor Eldridge is an 1838 historical account by Elleanor Eldridge and Frances Harriet Whipple Green. In the book, the authors describe how restorative sleep can be for young people, writing ___",
    content2: "Which quotation from Memoirs of Elleanor Eldridge most effectively illustrates the claim?",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "“Then let no one turn with too much $$fussiness$$ from the simple story of the humble Elleanor though it may contain few, or none, of the thrilling charms of poetry and passion. ",
    answerB:
      "Home is home, to the lowly as well as the great; and no rank, or color, destroys its sacred character, its power over the mind, and the affections. ",
    answerC:
      "Blessed are the slumbers of the innocent! They are kindlier than balm, and they refresh and gladden the spirit of childhood, like ministerings from a better world. ",
    answerD:
      "And now, dear reader, a word with you. What is done cannot be undone. We cannot unravel this web of iniquity, and extract justice from this mass of cruel wrongs. ",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Quotation",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "As exemplified by Yi songs about the natural environment and Tlingit songs about wildlife encounters, ecological information can be transmitted in Indigenous songs, and in some Instances is maintained only in this way. Kwaxsistalla Wathi'thia, a song keeper for the Kwakwaka'wakw people in Canada, collaborated with ethnobiologist Dana Lepofsky et al.. sharing songs referencing terraced intertidal clam gardens the people implemented in the past to foster healthy development of a dietary staple. Drawing on archaeological evidence as well, Lepofsky et al. determined that the prevalence of the practice described in the songs corresponded with growth in clam size and abundance despite increased harvesting pressure, a finding that demonstrates that,___",
    content2: "Which choice most logically completes the text?",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "representation of practical applications of ecological knowledge is the defining characteristic of the music of certain Indigenous peoples.",
    answerB:
      "the Kwakwaka'wakw people likely would not have detailed their creation of clam gardens in songs if their efforts had produced significantly larger clams.",
    answerC:
      "the clams harvested from intertidal terraces by Kwakwaka'wakw people in the past likely were a different species than the clams in those areas today.",
    answerD:
      "effective methods for the cultivation of sources of sustenance are among the ecological knowledge preserved in Indigenous songs.",
    correctAnswer: "D",
    testType: "Reading and Writing",
    tag1: "Complete",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1: "Correlation between Model-Predicted and Participant-Reported Enjoyment Ratings, by Painting Style",
    content2: "@@89-2-13@@",
    content3:
      "Neuroscientist Kiyohito Iigaya and colleagues developed a computational model to predict how much a person will enjoy a particular work of art on a scale from 1 (not at all) to 4 (very much). They then recruited participants to use the same scale to rate several sets of paintings in various styles and calculated the correlation between the ratings predicted by the model and those reported by the participants. Assuming participant P3 gave equal ratings to the impressionist and color-field paintings, the data in the graph suggest that the model predicted that ____",
    content4: "Which choice most effectively uses data from the graph to complete the text?",
    content5: "",
    answerA: "P3 would derive less aesthetic pleasure from impressionist paintings than from color-field paintings.",
    answerB: "P3 would derive more aesthetic pleasure from impressionist paintings than from color-field paintings.",
    answerC: "P3's ratings for impressionist and color-field paintings would differ from one another.",
    answerD: "P3's ratings for impressionist and color-field paintings would equal one another.",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Data",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "Like many other genera of wild bees, bumblebees have in recent decades experienced population collapse caused by, among other factors, habitat destruction and climate variation. Bumblebees are also one of the most researched bee genera, second only to honeybees. As a result, ecologists have gained much of their insight about wild-bee declines from bumblebees. In a 2021 paper, zoologist Guillaume Ghisbain notes that bumblebees are among the relatively few wild-bee genera that display social behaviors and dietary generalism (ability to obtain nectar and pollen from a diversity of plant species), two traits that are associated with increased resilience to some specific environmental changes. Ghisbain therefore contends that ____",
    content2: "Which choice most logically completes the text?",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "although bumblebees have been more extensively studied than most wild bees, researchers should not draw conclusions about the decline of other wild bees, even ones with feeding patterns and levels of sociability that are similar to those of bumblebees.",
    answerB:
      "because bumblebees and other bees with generalist diets are less negatively affected by environmental stress than bees with specialized diets are, they are less likely to experience major population changes in the future than bees with specialized diets are.",
    answerC:
      "because the responses of bumblebees and other wild bees to environmental threats are not always comparable, researchers need to exercise caution when extrapolating information about wild-bee population declines from bumblebees.",
    answerD:
      "although bumblebees and many other wild bees have experienced similar population declines in the past, compared with other wild bees, bumblebees are likely at greater risk of being harmed by climate variation than by habitat destruction.",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Complete",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "The dull forest hawkmoth, a large-bodied moth, defends itself against Arizona myotis and other insect-eating bats, which use echolocation to hunt, by emitting ultrasonic clicks that can, for instance, disrupt the bats' echolocation signals. To investigate moths' defensive ultrasound—which researchers had thought was exclusive to tiger moths, hawkmoths, and one species of geometer moths—Nicholas T. Homziak et al. recorded the responses of moths from 252 genera, representing most families of large-bodied moths, to audio playback of bat echolocation. The researchers found that 52 of the genera, including several genera belonging to the geometer family, produced defensive ultrasonic clicks. This result suggests that ____",
    content2: "Which choice most logically completes the text?",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "ultrasound production is only one of a diverse range of effective strategies moths employ to evade bat attacks.",
    answerB:
      "anti-bat ultrasound production may be a more prevalent defense strategy among large-bodied moths than previously known to researchers.",
    answerC:
      "unlike the 52 moth genera that emit ultrasonic clicks, most moth genera have likely not developed defenses specifically against bat attacks.",
    answerD:
      "some genera of large-bodied moths may use ultrasonic signaling for purposes other than avoiding capture by predators such as Arizona myotis.",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "Complete",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "The shesep, which is written as a long, horizontal hieroglyph shaped like a thumbless hand, and the heqat, which is written as a hieroglyph that looks like four oval items pouring out of a barrel, were ancient Egyptian units of measurement, and used ______ to record length and volume, respectively, the shesep and heqat have since fallen out of use.",
    content2: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "measurement, and used,",
    answerB: "measurement. Used",
    answerC: "measurement, used",
    answerD: "measurement used",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "Grammar",
    tag2: "Punctuation",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "In the Silurian hypothesis, astrophysicist Adam Frank and climatologist Gavin Schmidt suggest the geological record may contain evidence of prehuman advanced civilizations. This sensational hypothesis obscures the scientists' practical _____ . Frank and Schmidt don't believe such a civilization existed, and their \"hypothesis\" is a thought experiment exploring the traces our own civilization will leave on the geological record.",
    content2: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "aim, however,",
    answerB: "aim, however;",
    answerC: "aim. However,",
    answerD: "aim: however,",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "Grammar",
    tag2: "Punctuation",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "English poet and Shakespeare contemporary John Donne's _____ much admired during his lifetime (1572-1631) and in the decades that followed, had, at the time of their enthusiastic rediscovery by the early twentieth-century modernists, been essentially gathering dust for the intervening 250 years.",
    content2: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "works,",
    answerB: "works, were",
    answerC: "works were",
    answerD: "works had been",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Grammar",
    tag2: "Verb Choice",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "As of 2017, Italy's top tax rate of 55% was lower than the country's Laffer curve peak (70%). To some economists, whether a tax cut will ultimately increase Italy's tax revenue is dependent on the country's position on the Laffer a theoretical _____ relationship between tax rates and revenues, the curve was famously sketched on a napkin by economist Arthur Laffer in 1974.",
    content2: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "curve",
    answerB: "curve;",
    answerC: "curve, which is",
    answerD: "curve,",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "Grammar",
    tag2: "Punctuation",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "While the greater adjutant can be found in places like the Central Tanintharyi Coast in Myanmar and Dong Khanthung in Laos, more than 80 percent of this endangered stork species is found in Assam, India. There, wildlife biologist Dr Purnima Devi Barman is on the front lines of conservation efforts ____ through community involvement and scientific study, aim to bring adjutants back from near extinction.",
    content2: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "that:",
    answerB: "that;",
    answerC: "that,",
    answerD: "that—",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Grammar",
    tag2: "Punctuation",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      'O2 Arena," an award-winning science fiction story by Nigerian author Oghenechovwe Donald Ekpeki, takes place in an alternate version of Nigeria where breathable air is a rare commodity that is owned and sold by companies. ______ people must purchase it with currency called O2 credits.',
    content2: "Which choice completes the text with the most logical transition?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "Nevertheless,",
    answerB: "In any case,",
    answerC: "As a result,",
    answerD: "Earlier,",
    correctAnswer: "C",
    testType: "Reading and Writing",
    tag1: "Transition",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1:
      "In the 1880s, inventor Lewis Latimer improved upon Thomas Edison's design for the electric light bulb. Latimer ______ made the light bulb more durable by placing cardboard around its carbon filament. With this innovation, Latimer became the first Black inventor to contribute to the electrification of the world.",
    content2: "Which choice completes the text with the most logical transition?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "Soon,",
    answerB: "Regardless,",
    answerC: "However,",
    answerD: "Specifically,",
    correctAnswer: "D",
    testType: "Reading and Writing",
    tag1: "Transition",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1: "While researching a topic, a student makes the following notes:",
    content2:
      "- Samoil M. Bilenky is a Russian particle physicist.  - Particle physicists study subatomic particles.  - Neutrinos are some of the least understood subatomic particles.  - Neutrinos were first discovered in the mid-twentieth century.  - Bilenky is known for his research on neutrino oscillations.",
    content3:
      "The student wants to provide an example of a particle physicist whose research focuses on neutrinos. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    content4: "",
    content5: "",
    answerA: "Neutrinos are a type of subatomic particle that particle physicists are still trying to understand.",
    answerB: "Particle physicist Samoil M. Bilenky is known for his research on neutrino oscillations.",
    answerC:
      "The research done on neutrino oscillations exemplifies the work particle physicists do to advance our understanding of subatomic particles.",
    answerD:
      "By studying neutrino oscillations—to name just one example—particle physicists can learn more about neutrinos.",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "Notes",
    tag2: "Example",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1: "While researching a topic, a student makes the following notes:",
    content2:
      "- Minor planets are astronomical objects that orbit the Sun but are neither planets nor comets.  - Astronomer Jane Luu has discovered many minor planets in her career.  - Alongside colleagues David C. Jewitt and Chadwick Trujillo, she discovered the minor planet (19308) 1996 T066 on October 12, 1996.  - Alongside colleagues David C. Jewitt, Chadwick-Trujillo, and David J. Tholen, she discovered the minor planet (24978) 1998 HJ151 on April 28, 1998.",
    content3:
      "Which choice most effectively uses information from the given sentences to emphasize the discovery of (19308) 1996 T066 to an audience already familiar with Jane Luu?",
    content4: "",
    content5: "",
    answerA:
      "First there was the discovery of (19308) 1996 TO66 on October 12, 1996, and then on April 28, 1998, Jane Luu discovered yet another minor planer with the help of her colleagues David C. Jewitt, Chadwick Trujillo, and David J. Tholen.",
    answerB:
      "Astronomer Jane Luu helped discover not only the minor planet (19308) 1996 TO66 on October 12, 1996, but also (24978) 1998 HJ151 on April 28, 1998.",
    answerC:
      "Jane Luu is an astronomer famous for her discovery of many minor planets in our solar system, including (19308) 1996 TO66.",
    answerD:
      "On October 12. 1996, Jane Luu and her colleagues David C. Jewitt and Chadwick Trujillo made the exciting discovery of the minor planet (19308) 1996 TO66.",
    correctAnswer: "D",
    testType: "Reading and Writing",
    tag1: "Notes",
    tag2: "Familiar",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1: "While researching a topic, a student has taken the following notes:",
    content2:
      "- A supercontinent is a single landmass made up of most or all of Earth's continents.  - Over time, continents merge together to form supercontinents, which then break apart.  - This process is believed to take hundreds of millions of years and is known as the supercontinent cycle.  - Ur was a supercontinent that formed about 3.1 billion years ago.  - Columbia was a supercontinent that formed about 1.8 billion years ago.",
    content3:
      "The students wants to emphasize the order in which the supercontinents were formed. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    content4: "",
    content5: "",
    answerA: "The supercontinent Columbia formed long after the supercontinent Ur.",
    answerB: "Ur formed about 3.1 billion years ago but eventually broke apart.",
    answerC:
      "Forming and breaking apart over hundreds of millions of years, supercontinents are made up of most or all of Earth's continents",
    answerD:
      "Ur and Columbia were both supercontinents, single landmasses made up of most or all of Earth's continents.",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Notes",
    tag2: "Emphasize",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1: "While researching a topic, a student has taken the following notes:",
    content2:
      "- Catharsis, Conversion, Truumata is a 1986 sculpture by American artist Joseph Kosuth.It consists of a blue neon sign that spells out the title phrase.  - Harvest Moon is a 2013 sculpture by British/Pakistani artist Shezad Dawood.It consists of a yellow neon sign that forms an abstract moon shape.  - Neon signs became popular with advertisers in the 1920s and began to decline in popularity in the 1960s.  - Neon signs became popular with artists in the 1960s and continue to be popular today.",
    content3:
      "The student wants to emphasize a difference between the two sculptures. Which choice. most effectively uses relevant information from the notes to accomplish this goal?",
    content4: "",
    content5: "",
    answerA:
      "Molded into an evocative phrase in Catharsis, Conversion, Traumata (1986), an abstract form in Harvest Moon (2013), and an advertising tool in decades past, neon lighting has a number of different applications.",
    answerB:
      "While the sculptures share a common material, one spells out a phrase while the other is decidedly more abstract.",
    answerC:
      "Kosuth's sculpture was made in 1986 and Dawood's in 2013, both well after the advertising heyday of neon signs had passed.",
    answerD:
      "American artist joseph Kosuth's and British/Pakistani artist Shezad Dawood's sculptures have employed neon signs in different ways, demonstrating the versatility of the popular material.",
    correctAnswer: "B",
    testType: "Reading and Writing",
    tag1: "Notes",
    tag2: "Emphasize",
    tag3: "",
    tag4: "",
  },
  {
    module: 2,
    content1: "While researching a topic, a student makes the following notes:",
    content2:
      "- Stylistic analysis and biographical analysis are two approaches to art criticism.  - Stylistic analysis examines how an artwork's visual features contribute to its overall style.  - Such an analysis of Claude Monet's Water Lilies might consider how the painting's loose brushwork represents an impressionist style.  - Biographical analysis considers the personal experiences of the artist.  - Such an analysis of Claude Monet's Women in the Garden might consider how the painting's portrayal of a figure holding red and white roses alludes to Monet's romantic difficulties.",
    content3:
      "The student wants to present biographical analysis to an audience unfamiliar with the concept. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    content4: "",
    content5: "",
    answerA: "An approach to art criticism, biographical analysis considers the personal experiences of the artist.",
    answerB:
      "A stylistic analysis of Water Lilies might consider how the painting's loose brushwork represents an impressionist style.",
    answerC:
      "Stylistic analysis differs from biographical analysis in that stylistic analysis examines how an artwork's visual features contribute to its overall style.",
    answerD:
      "Women in the Garden's portrayal of a figure holding red and white roses alludes to Monet's romantic difficulties.",
    correctAnswer: "A",
    testType: "Reading and Writing",
    tag1: "Notes",
    tag2: "Unfamiliar",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 1,
    content1: "@@89-3-1@@",
    content2:
      "The scatterplot shows 5 measurements of the body length, in centimeters (cm), of a New Zealand fur seal from an age of 1 year to 6 years old. A line of best fit is also shown. For a New Zealand fur seal at an age of 3 years old. What is the body length predicted by the line of best fit to the nearest 10 cm?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "",
    answerB: "",
    answerC: "",
    answerD: "",
    correctAnswer: 110,
    testType: "Math",
    tag1: "Coordinate Geometry",
    tag2: "Scatterplot",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 2,
    content1: "The function $$f$$ is defined by $$f(x)=-4x+50$$. What is the value of $$f(x)$$ when $$x=-7$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: 39,
    answerB: 43,
    answerC: 46,
    answerD: 78,
    correctAnswer: "D",
    testType: "Math",
    tag1: "Algebra",
    tag2: "Linear Function",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 3,
    content1:
      "A botanist estimates the number of oak trees in a forest to be at least 2,600 and not more than 3,200. Which inequality best represents the number of oak trees, x, in the forest?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$x<=600$$",
    answerB: "$$x<=2,600$$",
    answerC: "$$2,600<=x<=3,200$$",
    answerD: "$$x<=2,600$$ or $$x>=3,200$$",
    correctAnswer: "C",
    testType: "Math",
    tag1: "Word Problem",
    tag2: "Inequality",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 4,
    content1: "@@89-3-4@@",
    content2:
      "In the figure shown, line $$l$$ intersects lines $$j$$ and $$k$$. Which additional piece of information is sufficient to prove that lines $$j$$ and $$k$$ are parallel?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$w=35$$",
    answerB: "$$w=145$$",
    answerC: "$$y=35$$",
    answerD: "$$z=145$$",
    correctAnswer: "A",
    testType: "Math",
    tag1: "Geometry",
    tag2: "Proof",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 5,
    content1: "Which expression is equivalent to $$11x^3+2x^2+7x$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$20(x^3+x^2+x)$$",
    answerB: "$$x(11x^2+2x+7)$$",
    answerC: "$$7x(11x^3+2x^2+1)$$",
    answerD: "$$11x(x^2+2x+7)$$",
    correctAnswer: "B",
    testType: "Math",
    tag1: "Algebra",
    tag2: "Equivalent Expression",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 6,
    content1: "Which expression is equivalent to $$(3nr^2+4nr)+(8n^{2r}+2nr)$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$11n^2r^2+6nr$$",
    answerB: "$$11n^3r^3+6n^2r^2$$",
    answerC: "$$24n^3r^3+8n^2r^2$$",
    answerD: "$$3nr^2+8n^{2r}+6nr$$",
    correctAnswer: "D",
    testType: "Math",
    tag1: "Algebra",
    tag2: "Equivalent Expression",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 7,
    content1: "How many centimeters are equivalent to 35 meters? (1 meter = 100 centimeters)",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "",
    answerB: "",
    answerC: "",
    answerD: "",
    correctAnswer: 3500,
    testType: "Math",
    tag1: "Word Problem",
    tag2: "Unit Conversion",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 8,
    content1: "@@89-3-8@@",
    content2: "What is the slope of the line shown?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "",
    answerB: "",
    answerC: "",
    answerD: "",
    correctAnswer: 0.5,
    testType: "Math",
    tag1: "Graph",
    tag2: "Linear Function",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 9,
    content1: "$$y=7,900(0.86)^x$$",
    content2:
      "The given equation estimates the value, in dollars, of a certain car $$x$$ years after it was purchased. According to the given equation, what was the estimated value, in dollars, of the car at the time it was purchased?",
    content3: "",
    content4: "",
    content5: "",
    answerA: 790,
    answerB: "6,794",
    answerC: "7,900",
    answerD: "8,600",
    correctAnswer: "C",
    testType: "Math",
    tag1: "Interpretation",
    tag2: "Exponential",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 10,
    content1: "@@89-3-10@@",
    content2: "Triangle XYZ shown is a right triangle. Which of the following has the same value as $$sin X$$?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$tan X$$",
    answerB: "$$tan Y$$",
    answerC: "$$cos X$$",
    answerD: "$$cos Y$$",
    correctAnswer: "D",
    testType: "Math",
    tag1: "Trigonometry",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 11,
    content1: "The function $$f$$ is defined by $$f(x)=3(\\frac{1}{4}-x)^2+\\frac{13}{4}$$. What is the value of $$f(\\frac{1}{4})$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "",
    answerB: "",
    answerC: "",
    answerD: "",
    correctAnswer: 3.25,
    testType: "Math",
    tag1: "Algebra",
    tag2: "Nonlinear Function",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 12,
    content1:
      "A survey was conducted in Franklin to estimate the percent of adult residents who support the addition of a parking garage in their town. Based on the survey, it is estimated that 77% of all adult residents of Franklin support the addition of a parking garage in their town, with an associated margin of error of 5%. Which of the following is the most appropriate conclusion about all adult residents of Franklin?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA:
      "Plausible values for the percent of all adult residents of Franklin who support the addition of a parking garage in their town are between 72% and 82%.",
    answerB:
      "The addition of a parking garage in the town is supported by exactly 72% of all adult residents of Franklin.",
    answerC:
      "Plausible values for the percent of all adult residents of Franklin who support the addition of a parking garage in their town are either less than 72% or more than 82%.",
    answerD:
      "The addition of a parking garage in the town is supported by more than 82% of all adult residents of Franklin.",
    correctAnswer: "A",
    testType: "Math",
    tag1: "Survey",
    tag2: "Margin of Error",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 13,
    content1: "$$3x+6rx=54$$",
    content2: "In the given equation, $$r$$ is a constant. The equation has no solution. What is the value of $$r$$?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$1/9$$",
    answerB: "$$-1/2$$",
    answerC: 2,
    answerD: 9,
    correctAnswer: "B",
    testType: "Math",
    tag1: "Algebra",
    tag2: "Linear Equation",
    tag3: "Number of Solutions",
    tag4: "",
  },
  {
    module: 3,
    question: 14,
    content1:
      "Line t in the xy-plane has a slope of $$1/3$$ and passes through the point (15,-6). Which equation defines line t?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$y=-11x+1/3$$",
    answerB: "$$y=x/3-11$$",
    answerC: "$$y=x/3-6$$",
    answerD: "$$y=15x-6$$",
    correctAnswer: "B",
    testType: "Math",
    tag1: "Algebra",
    tag2: "Graph",
    tag3: "Linear Equation",
    tag4: "Linear Regression",
  },
  {
    module: 3,
    question: 15,
    content1: "$$4(x-3)=13+2(x-3)$$",
    content2: "If $$x$$ is the solution to the given equation, what is the value of $$x-3$$?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "",
    answerB: "",
    answerC: "",
    answerD: "",
    correctAnswer: 6.5,
    testType: "Math",
    tag1: "Algebra",
    tag2: "Linear Equation",
    tag3: "Solve for Expression",
    tag4: "",
  },
  {
    module: 3,
    question: 16,
    content1:
      "The ratio of 12 to $$x$$ is equivalent to the ratio of 156 to $$y$$. Which expression represents $$y$$ in terms of $$x$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$1/(13)x$$",
    answerB: "$$13x$$",
    answerC: "$$1/(12)x$$",
    answerD: "$$12x$$",
    correctAnswer: "B",
    testType: "Math",
    tag1: "Algebra",
    tag2: "Ratio",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 17,
    content1:
      "Rectangles ABCD and EFGH are similar. The length of each side of EFGH is 6 times the length of the corresponding side of ABCD. The area of ABCD is 102 square units. What is the area, in square units, of EFGH?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: 17,
    answerB: 36,
    answerC: 612,
    answerD: "3,672",
    correctAnswer: "D",
    testType: "Math",
    tag1: "Geometry",
    tag2: "Area",
    tag3: "Similar",
    tag4: "Scale",
  },
  {
    module: 3,
    question: 18,
    content1: "$$1/x+1/(x-3)=6/(x^2-3x)$$",
    content2: "What are all the solutions to the given equation?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "6 and -1",
    answerB: "0 and 3",
    answerC: 3,
    answerD: "$$9/2$$",
    correctAnswer: "D",
    testType: "Math",
    tag1: "Algebra",
    tag2: "Nonlinear Equation",
    tag3: "PITA",
    tag4: "",
  },
  {
    module: 3,
    question: 19,
    content1:
      "Circle A in the xy-plane has the equation $$(x+2)^2+(y-2)^2=9$$. Circle B has the same center as circle A. The radius of circle B is two times the radius of circle A. The equation defining circle B in the xy-plane is $$(x+2)^2+(y-2)^2=k$$, where $$k$$ is a constant. What is the value of $$k$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "",
    answerB: "",
    answerC: "",
    answerD: "",
    correctAnswer: 36,
    testType: "Math",
    tag1: "Coordinate Geometry",
    tag2: "Circle",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 20,
    content1: "Number of queen ants|Number of colonies 1|11 2|9 3|1 4|6 5|6",
    content2:
      "Scientists collected acorns that each housed a colony of a particular ant species and then analyzed each colony’s structure. For these colonies, the table summarizes the number of queen ants per colony. For these colonies what is the median number of queen ants per colony?",
    content3: "",
    content4: "",
    content5: "",
    answerA: 6,
    answerB: 4,
    answerC: 3,
    answerD: 2,
    correctAnswer: "D",
    testType: "Math",
    tag1: "Statistics",
    tag2: "",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 21,
    content1: "@@89-3-21@@",
    content2:
      "The graph of $$y=f(x)-k$$ is shown in the xy-plane. If $$k$$, $$a$$, and $$b$$ are positive constants, which equation could define $$f$$?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$f(x)=(x-a)^2(x+b)$$",
    answerB: "$$f(x)=(x-a)^2(x-b)$$",
    answerC: "$$f(x)=(x-a)^2(x+b)^2$$",
    answerD: "$$f(x)=(x-a)^2(x-b)^2$$",
    correctAnswer: "A",
    testType: "Math",
    tag1: "Coordinate Geometry",
    tag2: "Zero to Factor",
    tag3: "",
    tag4: "",
  },
  {
    module: 3,
    question: 22,
    content1:
      "The linear function $$g$$ is defined by $$g(x)=b-15x$$, where $$b$$ is a constant. If $$g(c+7)=c/4$$ where $$c$$ is a constant, which of the following expressions represents the value of $$b$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$(15c)/4$$",
    answerB: "$$(19c)/4+7$$",
    answerC: "$$(61c)/4+105$$",
    answerD: "$$15c+105$$",
    correctAnswer: "C",
    testType: "Math",
    tag1: "Algebra",
    tag2: "Linear Function",
    tag3: "Plug In",
    tag4: "",
  },
  {
    module: 4,
    question: 1,
    content1:
      "As part of a science experiment on evaporation. Ella measured the height of water in a glass over a period of time. The function $$f(x)=39-0.18x$$ gives the estimated height, in centimeters (cm), of the water in the glass x days after the start of the experiment. Which of the following is the best interpretation of 39 in this context?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "The estimated height, in cm, of the water at the start of the experiment.",
    answerB: "The estimated height, in cm, of the water at the end of the experiment.",
    answerC: "The estimated change in the height, in cm, of the water each day.",
    answerD: "The estimated number of days for all the water to evaporate.",
    correctAnswer: "A",
    testType: "Math",
    tag1: "Interpretation",
    tag2: "Linear Function",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 2,
    content1: "Area (square feet)|Water (gallons) 2,520|4,536 3,780|6,804 5,040|9,072",
    content2:
      "The roofs on the buildings of a public garden are designed to allow water to drain into the garden. The table shows the relationship between the area $$x$$, in square feet, of a roof and the amount of water $$f(x)$$, in gallons, drained from the roof into the garden over a certain period of time. Which equation could define $$f$$?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$f(x)=0.6x$$",
    answerB: "$$f(x)=1.8x$$",
    answerC: "$$f(x)=2,268.0x$$",
    answerD: "$$f(x)=4,356.0x$$",
    correctAnswer: "B",
    testType: "Math",
    tag1: "Representation",
    tag2: "Linear Function",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 3,
    content1:
      "In 2010, a skating team had a total of 35 skaters, each classified as either advanced or intermediate. From 2010 to 2020, the number of advanced skaters on the team increased by approximately 53%, and the number of intermediate skaters on the team increased by approximately 44%. The total number of skaters on the team increased by approximately 49%. Which equation best represents this situation, where $$a$$ represents the number of advanced skaters on the team in 2010 and $$b$$ represents the number of intermediate skaters on the team in 2010?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$1.53a+1.49b=35(1.44)$$",
    answerB: "$$1.49a+0.53b=35(1.44)$$",
    answerC: "$$1.53a+1.44b=35(1.49)$$",
    answerD: "$$1.44a+1.53b=35(1.49)$$",
    correctAnswer: "C",
    testType: "Math",
    tag1: "Representation",
    tag2: "Linear Function",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 4,
    content1: "$$b-72=x/y$$",
    content2:
      "The given equation relates the positive numbers $$b$$, $$x$$, and $$y$$. Which equation correctly expresses $$x$$ in terms of $$b$$ and $$y$$?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$x=(b-72)/y$$",
    answerB: "$$x=by-72$$",
    answerC: "$$x=(by-72)/y$$",
    answerD: "$$x=by-72y$$",
    correctAnswer: "D",
    testType: "Math",
    tag1: "Algebra",
    tag2: "Linear Solving",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 5,
    content1: "$$y=2/7x+3$$",
    content2: "$$-7x-y=36$$",
    content3:
      "One of the two equations in a system of linear equations is given. The system has infinitely many solutions. If the second equation in the system is $$y=mx+b$$, where $$m$$ and $$b$$ are constants, what is the value of $$b$$?",
    content4: "",
    content5: "",
    answerA: "$$-3$$",
    answerB: "$$-1/3$$",
    answerC: "$$1/3$$",
    answerD: "$$3$$",
    correctAnswer: "D",
    testType: "Math",
    tag1: "Algebra",
    tag2: "Number of Solutions",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 6,
    content1: "$$y=6x+16$$",
    content2: "$$-7x-y=36$$",
    content3: "What is the solution $$(x,y)$$ to the given system of equations?",
    content4: "",
    content5: "",
    answerA: "$$(-4,-8)$$",
    answerB: "$$(-20/13,-80/13)$$",
    answerC: "$$(4,40)$$",
    answerD: "$$(20,136)$$",
    correctAnswer: "A",
    testType: "Math",
    tag1: "Coordinate Geometry",
    tag2: "System of Equations",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 7,
    content1: "@@89-4-7-1@@",
    content2: "@@89-4-7-2@@",
    content3:
      "The histograms summarize the distributions of scores for team A and team B. Which statement best compares the standard deviations of scores for these teams?",
    content4: "",
    content5: "",
    answerA: "The standard deviation of scores for team A is less than the standard deviation of scores for team B.",
    answerB: "The standard deviation of scores for team A is greater than the standard deviation of scores for team B.",
    answerC: "The standard deviation of scores for team A is equal to the standard deviation of scores for team B.",
    answerD: "There is not enough information to compare the standard deviations.",
    correctAnswer: "A",
    testType: "Math",
    tag1: "Statistics",
    tag2: "Standard Deviation",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 8,
    content1: "$$x^2-5x-24=0$$",
    content2: "What is the sum of the solutions to the given equation?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "",
    answerB: "",
    answerC: "",
    answerD: "",
    correctAnswer: 5,
    testType: "Math",
    tag1: "Algebra",
    tag2: "Nonlinear Equation",
    tag3: "Quadratic",
    tag4: "Sum of Solutions",
  },
  {
    module: 4,
    question: 9,
    content1: "@@89-4-9@@",
    content2:
      "The graph of $$y=f(x)$$ is shown, where $$f(x)=ab^x+c$$, and $$a$$, $$b$$, and $$c$$ are constants. For how many values of $$x$$ does $$f(x)=0$$?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "Three",
    answerB: "Two",
    answerC: "One",
    answerD: "Zero",
    correctAnswer: "D",
    testType: "Math",
    tag1: "Coordinate Geometry",
    tag2: "Nonlinear Function",
    tag3: "Exponential",
    tag4: "",
  },
  {
    module: 4,
    question: 10,
    content1:
      "The cost of renting a piece of construction equipment for up to 5 days is $270 for the first day and $135 for each additional day. Which of the following equations gives the cost $$y$$, in dollars, of renting the equipment for $$x$$ days, where $$x$$ is a positive integer and $$x<=5$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$y=135x+135$$",
    answerB: "$$y=270x-135$$",
    answerC: "$$y=135x-135$$",
    answerD: "$$y=135x+270$$",
    correctAnswer: "A",
    testType: "Math",
    tag1: "Representation",
    tag2: "Linear Equation",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 11,
    content1:
      "Function $$f$$ is a quadratic function where $$f(20)=0$$ and $$f(-4)=0$$. The graph of $$y=f(x)$$ in the $$xy$$-plane has a vertex at $$(r,-64)$$. What is the value of $$r$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "",
    answerB: "",
    answerC: "",
    answerD: "",
    correctAnswer: -12,
    testType: "Math",
    tag1: "Quadratic",
    tag2: "Nonlinear Function",
    tag3: "Vertex",
    tag4: "",
  },
  {
    module: 4,
    question: 12,
    content1:
      "The function $$f$$ gives the product of a number, $$x$$ , and a number that is 91 more than $$x$$. Which equation defines $$f$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$f(x)=x^2+x+91$$",
    answerB: "$$f(x)=x^2+91$$",
    answerC: "$$f(x)=x^2+91x$$",
    answerD: "$$f(x)=x^2+91x+91$$",
    correctAnswer: "C",
    testType: "Math",
    tag1: "Nonlinear Function",
    tag2: "Quadratic",
    tag3: "English to Math",
    tag4: "",
  },
  {
    module: 4,
    question: 13,
    content1: "$$-2x^2+20x+c=0$$",
    content2:
      "In the given equation, $$c$$ is a constant. The equation has exactly one solution. What is the value of $$c$$?",
    content3: "",
    content4: "",
    content5: "",
    answerA: -68,
    answerB: -50,
    answerC: -32,
    answerD: 0,
    correctAnswer: "B",
    testType: "Math",
    tag1: "Nonlinear Equation",
    tag2: "Quadratic",
    tag3: "Discriminant",
    tag4: "Number of Solutions",
  },
  {
    module: 4,
    question: 14,
    content1: "$$y=2x^2-15x+23$$",
    content2: "$$y=x+a$$",
    content3:
      "In the given system of equations, $$a$$ is a constant. The graphs of the equations in the given system intersect at exactly one point, $$(x,y)$$, in the xy-plane. What is the value of $$a$$?",
    content4: "",
    content5: "",
    answerA: -9,
    answerB: -4,
    answerC: 4,
    answerD: 9,
    correctAnswer: "A",
    testType: "Math",
    tag1: "System of Equations",
    tag2: "Nonlinear Equation",
    tag3: "Quadratic",
    tag4: "Number of Solutions",
  },
  {
    module: 4,
    question: 15,
    content1:
      "The positive number $$a$$ is 2,352% of the sum of the positive numbers $$b$$ and $$c$$, and $$b$$ is 84% of $$c$$. What percent of $$b$$ is $$a$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "5,152%",
    answerB: "2,436%",
    answerC: "51.52%",
    answerD: "24.36%",
    correctAnswer: "A",
    testType: "Math",
    tag1: "English to Math",
    tag2: "Percentage",
    tag3: "System of Equations",
    tag4: "",
  },
  {
    module: 4,
    question: 16,
    content1:
      "The functions $$f$$ and $$g$$ are defined by the given equations below, where $$x>=0$$. Which of the following equations displays, as a constant or coefficient, the minimum value of the function it defines, where $$x>=0$$?",
    content2: "I. $$f(x)=18(1.4)^{x+5}$$",
    content3: "II. $$f(x)=18(1.16)(1.4)^{x+3}$$",
    content4: "",
    content5: "",
    answerA: "I only",
    answerB: "II only",
    answerC: "I and II",
    answerD: "Neither I nor II",
    correctAnswer: "D",
    testType: "Math",
    tag1: "Nonlinear Function",
    tag2: "Equation Display",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 17,
    content1: "$$(12x+28)/4-s/13=r(x-8)$$",
    content2:
      "In the given equation, $$s$$ and $$r$$ are constants, and $$s>0$$. If the equation has infinitely many solutions, what is the value of $$s$$?",
    content3: "",
    content4: "",
    content5: "",
    answerA: "",
    answerB: "",
    answerC: "",
    answerD: "",
    correctAnswer: 403,
    testType: "Math",
    tag1: "Linear Equation",
    tag2: "Number of Solutions",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 18,
    content1:
      "The perimeter of an isosceles right triangle is $$18+18sqrt2$$ inches. What is the length, in inches, of the hypotenuse of this triangle?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$9$$",
    answerB: "$$9sqrt2$$",
    answerC: "$$18$$",
    answerD: "$$18sqrt2$$",
    correctAnswer: "C",
    testType: "Math",
    tag1: "Geometry",
    tag2: "Trigonometry",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 19,
    content1:
      "A right triangular pyramid has exactly six edges. Each of these edges is 96 centimeters long. If the surface area of the pyramid is $$ksqrt3$$ square centimeters, what is the value of $$k$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "",
    answerB: "",
    answerC: "",
    answerD: "",
    correctAnswer: 9216,
    testType: "Math",
    tag1: "Geometry",
    tag2: "3D Shape",
    tag3: "Pyramid",
    tag4: "Surface Area",
  },
  {
    module: 4,
    question: 20,
    content1:
      "The cost of renting a piece of construction equipment for up to 5 days is $270 for the first day and $135 for each additional day. Which of the following equations gives the cost $$y$$, in dollars, of renting the equipment for $$x$$ days, where $$x$$ is a positive integer and $$x<=5$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$y=135x+135$$",
    answerB: "$$y=270x-135$$",
    answerC: "$$y=135x-135$$",
    answerD: "$$y=135x+270$$",
    correctAnswer: "A",
    testType: "Math",
    tag1: "Representation",
    tag2: "Linear Equation",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 21,
    content1:
      "A line intersects two parallel lines, forming four acute angles and four obtuse angles. The measure of one of those eight angles is $$(7x-250)^{\\circ}$$. The sum of the measure of four of the eight angles is $$k^{\\circ}$$. Which of the following could NOT be equivalent to $$k$$, for all values of $$x$$?",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
    answerA: "$$-14x+1540$$",
    answerB: "$$-28x+1720$$",
    answerC: "$$14x-320$$",
    answerD: "$$360$$",
    correctAnswer: "A",
    testType: "Math",
    tag1: "Geometry",
    tag2: "Angles",
    tag3: "",
    tag4: "",
  },
  {
    module: 4,
    question: 22,
    content1: "$$7x+4y=3$$",
    content2: "$$35x+20y=15$$",
    content3:
      "For each real number $$r$$, which of the following points lies on the graph of each equation in the xy-plane for the given system?",
    content4: "",
    content5: "",
    answerA: "$$(r/5+3,-r/5+15)$$",
    answerB: "$$(-4r/7+3/7,r)$$",
    answerC: "$$(r,7r/4+3/4)$$",
    answerD: "$$(r,-4r/7+3/7)$$",
    correctAnswer: "B",
    testType: "Math",
    tag1: "System of Equations",
    tag2: "Infinite Solutions",
    tag3: "Plug In",
    tag4: "Coordinate Geometry",
  },
] as const
